/// Generated by AssetsRefGenerator - DO NOT MODIFY BY HAND
class Res {
  static const String aadhaar_icon_svg = "assets/svg/aadhaar_icon_svg.svg";
  static const String aadhar_verification =
      "assets/svg/aadhar_verification.svg";
  static const String account_number = "assets/svg/account_number.svg";
  static const String account_number_png = "assets/account_number_png.png";
  static const String appform_rejected_svg =
      "assets/svg/appform_rejected_svg.svg";
  static const String appformRejectedMan = "assets/svg/rejected_man.svg";
  static const String applicationInProgress =
      "assets/svg/applicationInProgress.svg";
  static const String Bank = "assets/svg/Bank.svg";
  static const String bank_statement_illustration =
      "assets/svg/bank_statement_illustration.svg";
  static const String bank_svg = "assets/svg/bank_svg.svg";
  static const String bank_verify_failure =
      "assets/svg/bank_verify_failure.svg";
  static const String bank_verify_success =
      "assets/svg/bank_verify_success.svg";
  static const String benefit_one_svg = "assets/svg/benefit_one_svg.svg";
  static const String bg_confetti = "assets/svg/bg_confetti.svg";
  static const String blub = "assets/svg/blub.svg";
  static const String building = "assets/svg/building.svg";
  static const String bulb_icon = "assets/svg/bulb_icon.svg";

  static const String cake_png = "assets/svg/cake_png.png";
  static const String calenderImg = "assets/svg/calenderImg.svg";
  static const String camera = "assets/svg/permissions/camera.svg";
  static const String filesAndMedia =
      "assets/svg/permissions/files_and_media_svg.svg";
  static const String chevron_down_svg = "assets/svg/chevron_down_svg.svg";
  static const String city = "assets/svg/city.svg";
  static const String CKYC_missing = "assets/svg/CKYC_missing.svg";

  static const String close_no_outline = "assets/svg/close_no_outline.svg";
  static const String close_mark_svg = "assets/svg/close_mark_svg.svg";
  static const String close_x_mark_svg = "assets/svg/close_x_mark_svg.svg";
  static const String Company_png = "assets/Company_png.png";
  static const String confetti = "assets/svg/confetti.svg";

  static const String confirm_account_number_png =
      "assets/confirm_account_number_png.png";
  static const String credit_line_created =
      "assets/svg/credit_line_created.svg";
  static const String credit_line_rejected =
      "assets/svg/credit_line_rejected.svg";
  static const String default_bank = "assets/svg/default_bank.svg";
  static const String digi_locker_logo_svg =
      "assets/svg/digi_locker_logo_svg.svg";
  static const String digio_page_placeholder_svg =
      "assets/svg/digio_page_placeholder_svg.svg";
  static const String disabled_card_pattern =
      "assets/svg/disabled_card_pattern.svg";
  static const String disabled_inverted_card_pattern =
      "assets/svg/disabled_inverted_card_pattern.svg";
  static const String discount = "assets/svg/discount.svg";
  static const String document = "assets/svg/document.svg";
  static const String dollar = "assets/svg/dollar.svg";
  static const String download = "assets/svg/download.svg";
  static const String download_icon = "assets/download_icon.png";
  static const String Due_Date = "assets/svg/Due_Date.svg";
  static const String e_mandate_success = "assets/svg/e_mandate_success.svg";
  static const String e_sign = "assets/svg/e_sign.svg";
  static const String e_sign_verified = "assets/svg/e_sign_verified.svg";
  static const String Email = "assets/svg/Email.svg";
  static const String emandate = "assets/svg/emandate.svg";
  static const String emandate_failure = "assets/svg/emandate_failure.svg";
  static const String employment_type_svg =
      "assets/svg/employment_type_svg.svg";
  static const String employment_type = "assets/employment_type.png";
  static const String error_dialog_illustration =
      "assets/error_dialog_illustration.png";
  static const String eSignImg = "assets/svg/eSignImg.svg";
  static const String failedTriangleSVG = "assets/svg/failed_triangle_svg.svg";
  static const String fastTrackSVG = "assets/svg/fast_track_svg.svg";
  static const String feedback = "assets/svg/feedback.svg";
  static const String feedback_success = "assets/svg/feedback_success.svg";
  static const String Figtree_Black = "assets/fonts/figtree/Figtree-Black.ttf";
  static const String Figtree_BlackItalic =
      "assets/fonts/figtree/Figtree-BlackItalic.ttf";
  static const String Figtree_Bold = "assets/fonts/figtree/Figtree-Bold.ttf";
  static const String Figtree_BoldItalic =
      "assets/fonts/figtree/Figtree-BoldItalic.ttf";
  static const String Figtree_ExtraBold =
      "assets/fonts/figtree/Figtree-ExtraBold.ttf";
  static const String Figtree_ExtraBoldItalic =
      "assets/fonts/figtree/Figtree-ExtraBoldItalic.ttf";
  static const String Figtree_Italic =
      "assets/fonts/figtree/Figtree-Italic.ttf";
  static const String Figtree_Light = "assets/fonts/figtree/Figtree-Light.ttf";
  static const String Figtree_LightItalic =
      "assets/fonts/figtree/Figtree-LightItalic.ttf";
  static const String Figtree_Medium =
      "assets/fonts/figtree/Figtree-Medium.ttf";
  static const String Figtree_MediumItalic =
      "assets/fonts/figtree/Figtree-MediumItalic.ttf";
  static const String Figtree_Regular =
      "assets/fonts/figtree/Figtree-Regular.ttf";
  static const String Figtree_SemiBold =
      "assets/fonts/figtree/Figtree-SemiBold.ttf";
  static const String Figtree_SemiBoldItalic =
      "assets/fonts/figtree/Figtree-SemiBoldItalic.ttf";
  static const String google = "assets/google.png";

  static const String green_shield_svg = "assets/svg/green_shield_svg.svg";
  static const String hamburger = "assets/svg/hamburger.svg";

  static const String iconneed_help = "assets/svg/iconneed_help.svg";
  static const String ID = "assets/svg/ID.svg";
  static const String ifsc_code_png = "assets/ifsc_code_png.png";
  static const String income_type_svg = "assets/svg/income_type_svg.svg";
  static const String info_bulb = "assets/svg/info_bulb.svg";
  static const String info_icon = "assets/svg/info_icon.svg";
  static const String information_svg = "assets/svg/information_svg.svg";
  static const String intrest_down_arrow_svg =
      "assets/svg/intrest_down_arrow_svg.svg";
  static const String inverted_enabled_card_pattern =
      "assets/svg/inverted_enabled_card_pattern.svg";
  static const String loading_paper_flight_lottie =
      "assets/json/loading_paper_flight_lottie.json";
  static const String location = "assets/svg/permissions/location.svg";
  static const String location_colored = "assets/svg/location_colored.svg";
  static const String logout_dialog = "assets/logout_dialog.png";
  static const String mailImg = "assets/svg/mailImg.svg";
  static const String newMailSvg = "assets/svg/newMailSvg.svg";
  static const String Money = "assets/svg/Money.svg";
  static const String Next_EMI = "assets/svg/Next_EMI.svg";
  static const String no_pending_dues = "assets/svg/no_pending_dues.svg";
  static const String npci = "assets/svg/npci.svg";
  static const String offer_expired_clock_svg =
      "assets/svg/offer_expired_clock_svg.svg";
  static const String password_success = "assets/svg/password_success.svg";
  static const String pattern_complete = "assets/svg/pattern_complete.svg";
  static const String pdf = "assets/svg/pdf.svg";
  static const String pencil_icon = "assets/svg/pencil_icon.svg";
  static const String phoneImg = "assets/svg/phoneImg.svg";
  static const String newPhoneSvg = "assets/svg/newPhoneSvg.svg";
  static const String piggy_bank_failure_svg =
      "assets/svg/piggy_bank_failure_svg.svg";
  static const String policy_benefit_cf_svg =
      "assets/svg/policy_benefit_cf_svg.svg";
  static const String policy_benefit_ci_svg =
      "assets/svg/policy_benefit_ci_svg.svg";
  static const String policy_benefit_fc_svg =
      "assets/svg/policy_benefit_fc_svg.svg";
  static const String policy_benefit_fi_svg =
      "assets/svg/policy_benefit_fi_svg.svg";
  static const String policy_benefit_hcb_svg =
      "assets/svg/policy_benefit_hcb_svg.svg";
  static const String policy_benefit_hd_svg =
      "assets/svg/policy_benefit_hd_svg.svg";
  static const String policy_benefit_jl_svg =
      "assets/svg/policy_benefit_jl_svg.svg";
  static const String policy_benefit_msp_svg =
      "assets/svg/policy_benefit_msp_svg.svg";
  static const String policy_benefit_picod_svg =
      "assets/svg/policy_benefit_picod_svg.svg";
  static const String policy_benefit_ppd_svg =
      "assets/svg/policy_benefit_ppd_svg.svg";
  static const String policy_benefit_ptd_svg =
      "assets/svg/policy_benefit_ptd_svg.svg";
  static const String privo_logo = "assets/svg/privo_logo.svg";
  static const String Privo_logo_int = "assets/Privo_logo_int.png";
  static const String Privo_Playstore_logo = "assets/Privo_Playstore_logo.png";
  static const String processing_application =
      "assets/json/processing_application.json";
  static const String Profile = "assets/svg/Profile.svg";
  static const String profileUser = "assets/svg/profile-user.svg";
  static const String purpose = "assets/svg/purpose.svg";

  static const String registered_svg = "assets/svg/registered_svg.svg";
  static const String Rejected = "assets/svg/Rejected.svg";
  static const String rejected_document = "assets/svg/rejected_document.svg";
  static const String Relax = "assets/svg/Relax.svg";
  static const String ResidenceTypeSVG = "assets/svg/residence_type_svg.svg";
  static const String rounded_clear_icon = "assets/svg/rounded_clear_icon.svg";
  static const String sad_illustration = "assets/svg/sad_illustration.svg";
  static const String Salaried = "assets/svg/Salaried.svg";
  static const String same_offer_svg = "assets/svg/same_offer_svg.svg";
  static const String secure = "assets/svg/secure.svg";
  static const String self_employed = "assets/svg/self_employed.svg";
  static const String selfie_verification =
      "assets/svg/selfie_verification.svg";
  static const String sparkleSVG = "assets/svg/sparkle_svg.svg";

  static const String sparkle = "assets/svg/sparkle.svg";
  static const String splash_logo_bindaas_png =
      "assets/splash_logo_bindaas_png.png";
  static const String tenure = "assets/svg/tenure.svg";
  static const String verified_svg = "assets/svg/verified_svg.svg";

  static const String vkyc_bulb_svg = "assets/svg/vkyc_bulb_svg.svg";
  static const String vkyc_clock_svg = "assets/svg/vkyc_clock_svg.svg";
  static const String vkyc_access_svg = "assets/svg/vkyc_access_svg.svg";
  static const String vkyc_pan_svg = "assets/svg/vkyc_pan_svg.svg";
  static const String vkyc_wifi_svg = "assets/svg/vkyc_wifi_svg.svg";

  static const String web_svg = "assets/svg/web_svg.svg";
  static const String welcome_four_svg = "assets/svg/welcome_four_svg.svg";
  static const String welcome_one_svg = "assets/svg/welcome_one_svg.svg";
  static const String welcome_three_svg = "assets/svg/welcome_three_svg.svg";
  static const String welcome_two_svg = "assets/svg/welcome_two_svg.svg";
  static const String withdrawal_home_icon =
      "assets/svg/withdrawal_home_icon.svg";
  static const String withdrawal_location_icon =
      "assets/svg/withdrawal_location_icon.svg";
  static const String withdrawal_pattern = "assets/svg/withdrawal_pattern.svg";
  static const String wIthdrawal_success = "assets/svg/wIthdrawal_success.svg";
  static const String world_wide_web = "assets/svg/world-wide-web.svg";
  static const String pan = "assets/svg/pan.svg";
  static const String pan_verify_success = "assets/svg/pan_verify_success.svg";
  static const String withdrawal_processing =
      "assets/svg/withdrawal_processing.svg";
  static const String withdrawal_polling_svg =
      "assets/svg/withdrawal_polling_svg.svg";
  static const String cashout_polling = "assets/lottie/cashout_polling.json";
  static const String offer_polling = "assets/lottie/offer_polling.json";
  static const String penny_testing_polling =
      "assets/lottie/penny_testing_polling.json";
  static const String creditScoreRefreshSparkles =
      "assets/lottie/credit_score_refresh_sparkles.json";
  static const String aa_polling = "assets/svg/aa_polling.svg";
  static const String aa_success = "assets/svg/aa_success.svg";
  static const String withdraw_success = "assets/svg/withdraw_success.svg";
  static const String applicationInProgressFull =
      "assets/svg/applicationInProgressFull.svg";
  static const String eSignAgreement = "assets/svg/eSignAgreement.svg";
  static const String relaxImg = "assets/svg/relaxImg.svg";
  static const String partner_home_screen =
      "assets/svg/partner_home_screen.svg";
  static const String eSignBg = "assets/svg/e_sign_bg.svg";

  static const String poorIcon = "assets/svg/app_rating/poor_icon.svg";
  static const String average_selected =
      "assets/svg/app_rating/average_selected.svg";
  static const String average_unselected =
      "assets/svg/app_rating/average_unselected.svg";
  static const String excellent_selected =
      "assets/svg/app_rating/excellent_selected.svg";
  static const String excellent_unselected =
      "assets/svg/app_rating/excellent_unselected.svg";
  static const String good_selected = "assets/svg/app_rating/good_selected.svg";
  static const String good_unselected =
      "assets/svg/app_rating/good_unselected.svg";
  static const String okay_selected = "assets/svg/app_rating/okay_selected.svg";
  static const String okay_unselected =
      "assets/svg/app_rating/okay_unselected.svg";
  static const String poor_icon_selected =
      "assets/svg/app_rating/poor_icon_selected.svg";
  static const String success_icon = "assets/svg/success_icon.svg";

  static const String coinImg = "assets/svg/coin.svg";
  static const String rightArrow = "assets/svg/right_arrow.svg";
  static const String offerTimer = "assets/svg/offer_timer.svg";
  static const String offer_upgraded_svg = "assets/svg/offer_upgraded_svg.svg";
  static const String starUpgrade = "assets/svg/star_upgrade.svg";
  static const String lowGrowSuccessImg = "assets/svg/upgrade_success.svg";
  static const String lowGrowFailureImg = "assets/svg/low_grow_failure_img.svg";
  static const String lowGrowCancelSign = "assets/svg/low_grow_cancel_sign.svg";
  static const String fadeCoinLimit = "assets/svg/fade_coin_limit.svg";
  static const String fadeCoinTenure = "assets/svg/fade_coin_tenure.svg";
  static const String fadeCoinRoi = "assets/svg/fade_coin_roi.svg";
  static const String lowGrowTenure = "assets/svg/low_grow_tenureImg.svg";
  static const String lowGrowLimit = "assets/svg/low_and_grow_limitImg.svg";
  static const String maximizeSVG = "assets/svg/maximize_svg.svg";
  static const String minimizeSVG = "assets/svg/minimize_svg.svg";
  static const String chevronUp = "assets/svg/chevron-up.svg";
  static const String sparkleIcon = "assets/svg/sparkle_icon.svg";
  static const String singleSpark = "assets/svg/single_spark.svg";
  static const String addedBenefitInterestRate =
      "assets/svg/interest_rate_icon.svg";
  static const String greenCheckStepper = "assets/svg/green_check_stepper.svg";
  static const String borrowBanner = "assets/svg/borrow_Img.svg";
  static const String repayBanner = "assets/svg/repay_Img.svg";
  static const String reuseBanner = "assets/svg/reuse_Img.svg";
  static const String spendBanner = "assets/svg/spend_Img.svg";
  static const String ringImg = "assets/svg/ring_Img.svg";
  static const String travelIcon = "assets/svg/travel_icon.svg";
  static const String homePaintIcon = "assets/svg/home_paint_icon.svg";
  static const String dreamRideIcon = "assets/svg/dream_ride_icon.svg";
  static const String shoppingIcon = "assets/svg/shopping_icon.svg";
  static const String medicalIcon = "assets/svg/medical_icon.svg";
  static const String mobile_otp_svg = "assets/svg/mobile_otp_svg.svg";
  static const String educationIcon = "assets/svg/education_icon.svg";
  static const String arrow_right = "assets/svg/arrow_right.svg";
  static const String circularRightArrow =
      "assets/svg/circular_right_arrow.svg";
  static const String upi_white_logo = "assets/svg/upi_white_logo.svg";
  static const String upi_grey_logo = "assets/svg/upi_grey_logo.svg";
  static const String upi_blue_logo = "assets/svg/upi_blue_logo.svg";
  static const String upload_pdf_svg = "assets/svg/upload_pdf_svg.svg";
  static const String birdImg = "assets/svg/bird_img.svg";
  static const String rejectedBird = "assets/svg/rejected_bird.svg";
  static const String loanApplicationBlog = "assets/loan_application_blog.png";
  static const String blogPerson = "assets/blog_person.png";
  static const String youtubeThumbnail = "assets/youtube_thumbnail.png";
  static const String locationUnserviceable =
      "assets/svg/location_unservicable.svg";

  static const String credit_score = "assets/credit_score.png";
  static const String dti = "assets/dti.png";
  static const String fire = "assets/fire.png";
  static const String loanRejectionVideo = "assets/loan_rejection.png";
  static const String unlock_icon = "assets/svg/unlock_icon.svg";

  static const String lowGrowProcessingFee =
      "assets/svg/low_Grow_processing_fee.svg";
  static const String fadeCoinPf = "assets/svg/fade_coin_pf.svg";
  static const String likeIcon = "assets/svg/like_icon.svg";
  static const String blogFacebookIcon = "assets/svg/blog_facebook_icon.svg";
  static const String blogWhatsappIcon = "assets/svg/blog_whatsapp_icon.svg";
  static const String blogInstagramIcon = "assets/svg/blog_instagram_icon.svg";

  static const String roundedDisLikeIcon =
      "assets/svg/rounded_dislike_icon.svg";
  static const String roundedLikeIcon = "assets/svg/rounded_like_icon.svg";

  static const String splashLogo = "assets/svg/splash_logo.svg";
  static const String poweredByCS = "assets/svg/powered_by_cs.svg";
  static const String poweredByCSSmall = "assets/svg/powered_by_cs_small.svg";
  static const String warning = "assets/svg/warning.svg";
  static const String white_info = "assets/svg/white_info.svg";
  static const String question_icon = "assets/svg/question_icon.svg";
  static const String emi = "assets/svg/emi.svg";
  static const String fundTransfer = "assets/svg/fund_transfer.svg";
  static const String instant = "assets/svg/instant.svg";
  static const String interestAmount = "assets/svg/interest_amount.svg";
  static const String paperless = "assets/svg/paperless.svg";
  static const String goldenCoinsFallingPng =
      "assets/svg/golden_falling_coins.png";
  static const String coinsHomePageCard = "assets/svg/coins_home_page_card.svg";
  static const String arrow_dark = "assets/svg/arrow_dark.svg";
  static const String upgradeOfferAlert = "assets/svg/upgrade_offer_alert.svg";
  static const String offerExpiryAlert = "assets/svg/home_page/expiry.svg";
  static const String creditLineExpiryAlert =
      "assets/svg/credit_line_expiry_alert.svg";
  static const String expiryTimer = "assets/svg/expiry_timer.svg";
  static const String left_arrow = "assets/svg/left_arrow.svg";
  static const String chinese_coin = "assets/svg/chinese_coin.svg";
  static const String sort = "assets/svg/sort_asc.svg";
  static const String filter = "assets/svg/filter.svg";
  static const String filterNew = "assets/svg/FilterNew.svg";
  static const String filter_list = "assets/svg/filter_list.svg";
  static const String clear_filter = "assets/svg/clear_filter.svg";
  static const String danger = "assets/svg/danger.svg";
  static const String red_info_icon = "assets/svg/red_info_icon.svg";
  static const String topRightBlueArrowSVG =
      "assets/svg/top_right_blue_arrow_svg.svg";
  static const String logoutSVG = "assets/svg/logout_svg.svg";
  static const String avaialable_wallet = "assets/svg/available_wallet.svg";
  static const String used_limit_wallet = "assets/svg/used_limit_wallet.svg";
  static const String home_page_coin = "assets/svg/home_page_coin.svg";
  static const String right_tick = "assets/svg/right_tick.svg";
  static const String eMandateSVG = "assets/svg/e_mandate_svg.svg";
  static const String eMandateFailureSVG =
      "assets/svg/e_mandate_failure_svg.svg";
  static const String cardDetailsSVG = "assets/svg/card_details_svg.svg";
  static const String autoPaySuccessSVG = "assets/svg/auto_pay_success_svg.svg";

  static const String eNachDarkSVG = "assets/svg/e_nach_dark_svg.svg";
  static const String eNachLiteSVG = "assets/svg/e_nach_lite_svg.svg";

  static const String advance_emi_alert =
      "assets/svg/home_page/advance_emi_alert.svg";
  static const String low_and_grow_alert = "assets/svg/home_page/low_grow.svg";
  static const String exploreBlogsDoubleArrowSVG =
      "assets/svg/home_page/explore_blogs_double_arrow.svg";
  static const String faq = "assets/svg/faq.svg";
  static const String faqBgCircle1 = "assets/svg/faq_bg_circle1.svg";
  static const String helpAppBar = "assets/svg/help_appbar.svg";
  static const String creditScorePolling =
      "assets/svg/credit_score_polling.svg";
  static const String creditScorePollingSuccess =
      "assets/svg/credit_score_polling_success.svg";
  static const String creditReportHome = "assets/svg/credit_report_home.svg";
  static const String cibilLogo = "assets/cibil_logo.png";
  static const String creditReportBank = "assets/svg/credit_report_bank.svg";
  static const String creditTransactionNA =
      "assets/svg/credit_transaction_na.svg";
  static const String creditScoreScale = "assets/svg/credit_score_scale.svg";
  static const String eyeOpened = "assets/svg/eye_opened.svg";
  static const String eyeClosed = "assets/svg/eye_closed.svg";
  static const String creditScoreStar = "assets/svg/credit_score_star.svg";
  static const String creditScorePoor = "assets/svg/credit_score_poor.svg";
  static const String creditScoreLow = "assets/svg/credit_score_low.svg";
  static const String creditScoreFair = "assets/svg/credit_score_fair.svg";
  static const String creditScoreVeryGood =
      "assets/svg/credit_score_very_good.svg";
  static const String creditScoreExcellent =
      "assets/svg/credit_score_excellent.svg";
  static const String creditScoreConfetti =
      "assets/svg/credit_score/credit_score_confetti.svg";
  static const String creditCardIcon = "assets/svg/credit_card_icon.svg";
  static const String kycSuccessfull = "assets/svg/kyc_successfull.svg";
  static const String accountVerificationSuccess =
      "assets/svg/account_verification_success.svg";
  static const String homePageBNVHomeIconSVG =
      "assets/svg/home_page_bnv_home_icon_svg.svg";
  static const String homePageBNVLoanIconSVG =
      "assets/svg/home_page_bnv_loans_icon_svg.svg";

  static const String tenure_calendar = "assets/svg/tenure_calender.svg";
  static const String noLoansSVG = "assets/svg/all_loans/no_loans.svg";
  static const String upcomingEMISVG = "assets/svg/upcoming_emi_svg.svg";
  static const String textFieldErrorIcon = "assets/svg/error_icon.svg";
  static const String deleteArrow = "assets/svg/delete_arrow.svg";
  static const String deleteRequestSuccessFull = "assets/svg/delete_succes.svg";
  static const String faqDetailsLeftBg = "assets/svg/faq_details_left_bg.svg";
  static const String faqDetailsRightBg = "assets/svg/faq_details_right_bg.svg";
  static const String aadhaarLogo = "assets/aadhaar_logo.png";
  static const String aadharIcon = "assets/svg/aadhar_icon.svg";
  static const String selfieIcon = "assets/svg/selfie_icon.svg";
  static const String editIcon = "assets/svg/edit_icon.svg";
  static const String idCardIcon = "assets/svg/id_card_icon.svg";
  static const String okycExpired = "assets/svg/okyc_expired.svg";
  static const String vkycAttemptsReached =
      "assets/svg/vkyc_attempts_reached.svg";
  static const String vkycError = "assets/svg/vkyc_error.svg";
  static const String raiseIssue = "assets/svg/raise_issue.svg";
  static const String greenArrowDownLeftSvg =
      "assets/svg/green_arrow_down_left.svg";
  static const String blueArrowUpRightSvg =
      "assets/svg/blue_arrow_up_right.svg";

  ///EmiCalculator
  static const String calculateIcon = "assets/svg/emi_calculator/calculate.svg";
  static const String compareArrows =
      "assets/svg/emi_calculator/compare_arrows.svg";
  static const String encrypted = "assets/svg/emi_calculator/encrypted.svg";
  static const String language = "assets/svg/emi_calculator/language.svg";
  static const String schedule = "assets/svg/emi_calculator/schedule.svg";
  static const String lapIcon = "assets/svg/emi_calculator/lap.svg";
  static const String personalLoanIcon =
      "assets/svg/emi_calculator/personal_loan.svg";
  static const String sblIcon = "assets/svg/emi_calculator/sbl.svg";
  static const String bussinesLoanIcon =
      "assets/svg/emi_calculator/bussiness_loan.svg";
  static const String creditLineIcon =
      "assets/svg/emi_calculator/credit_line.svg";
  static const String equipmentFinLoan =
      "assets/svg/emi_calculator/equipment_fin_loan.svg";
  static const String workingCapIcon =
      "assets/svg/emi_calculator/working_cap.svg";
  static const String vacationLoan =
      "assets/svg/emi_calculator/vacation_loan.svg";

  ///Splash screen
  static const String splashBackGround =
      "assets/svg/splash/splash_background.svg";
  static const String csIndiaLogo = "assets/svg/splash/cs_india_logo.svg";
  static const String splashScreenLottieFile ="assets/splashScreenAnimation.json";

  // SBL- Business Details
  static const String businessEntityTFSvg =
      "assets/svg/business_entity_tf_svg.svg";
  static const String businessPanTFSvg = "assets/svg/business_pan_tf_svg.svg";
  static const String ownershipTypeTFSvg =
      "assets/svg/ownership_type_tf_svg.svg";
  static const String registrationDateTFSvg =
      "assets/svg/registration_date_tf_svg.svg";
  static const String dropDownTFSvg = "assets/svg/drop_down_tf_svg.svg";

  static const String soleProprietorIconSVG =
      "assets/svg/sole_proprietor_icon_svg.svg";
  static const String partnerShipIconSVG =
      "assets/svg/partnership_icon_svg.svg";
  static const String llpIconSVG = "assets/svg/llp_icon_svg.svg";
  static const String infoIconSVG = "assets/svg/info_icon_svg.svg";
  static const String designationTFSVG = "assets/svg/designation_tf_svg.svg";
  static const String shareHoldingTFSVG = "assets/svg/shareholding_tf_svg.svg";
  static const String rightCircleArrowIconSVG =
      "assets/svg/right_circle_arrow_icon_svg.svg";
  static const String getStartedSbl = "assets/svg/get_started_sbl.svg";
  static const String knowMoreCollateral =
      "assets/svg/know_more_collateral.svg";
  static const String knowMoreFast = "assets/svg/know_more_fast.svg";
  static const String knowMoreLoan = "assets/svg/know_more_loan.svg";
  static const String knowMorePercentage =
      "assets/svg/know_more_percentage.svg";
  static const String knowMoreTopUp = "assets/svg/know_more_top_up.svg";
  static const String ratingStar = "assets/svg/rating_star.svg";
  static const String documentIcon = "assets/svg/document_icon.svg";
  static const String udyamCertificate = "assets/svg/udyam_certificate.svg";
  static const String gstCertificate = "assets/svg/gst_certificate.svg";
  static const String rightDirectionArrow =
      "assets/svg/right_direction_arrow.svg";
  static const String pdDob = "assets/svg/pd_dob.svg";
  static const String pdEmail = "assets/svg/pd_email.svg";
  static const String pdName = "assets/svg/pd_name.svg";
  static const String pdPan = "assets/svg/pd_pan.svg";
  static const String pdLocation = "assets/svg/pd_location.svg";
  static const String pdResidence = "assets/svg/pd_residence.svg";
  static const String businessOwnerIcon = "assets/svg/business_owner_icon.svg";
  static const String selfEmployedIcon = "assets/svg/self_employed_icon.svg";
  static const String salariedIcon = "assets/svg/salaried_icon.svg";
  static const String panFieldInfo = "assets/svg/pan_field_info.svg";

  static const String emiCalculator =
      "assets/svg/emi_calculator/emi_calculator.svg";

  ///Revamped Intro Screen
  static const String sblIntro = "assets/svg/sbl_intro.svg";
  static const String loanManagementIntro =
      "assets/svg/loan_managment_intro.svg";
  static const String checkCircle = "assets/svg/intro_screen/check_circle.svg";

  ///permission screen
  static const String dataSafety = "assets/svg/permissions/data_safety.svg";
  static const String dataSafetyBackground =
      "assets/svg/permissions/data_safety_background.svg";
  static const String sms = "assets/svg/permissions/sms.svg";

  ///Our Partners
  static const String cred = "assets/partner/cred.svg";
  static const String lendingKart = "assets/partner/lending_kart.svg";
  static const String moneyView = "assets/partner/money_view.svg";
  static const String airtel = "assets/partner/airtel.svg";
  static const String paisaBazaar = "assets/partner/paisa_bazaar.svg";

  ///Home page
  static const String sblHomePageCard =
      "assets/svg/home_page/sbl_home_page_card.svg";
  static const String privoHomePageCard =
      "assets/svg/home_page/privo_instant_loan.svg";
  static const String sblDisbursalWait =
      "assets/svg/home_page/sbl_disbursal_wait.svg";
  static const String creditReport = "assets/svg/home_page/credit_report.svg";
  static const String offerBaloons = "assets/svg/home_page/offer_baloons.svg";
  static const String expandArrow = "assets/svg/home_page/expand_arrow.svg";
  static const String collapseArrow = "assets/svg/home_page/collapse_arrow.svg";
  static const String overdueClock = "assets/svg/home_page/overdue_clock.svg";
  static const String checkCircleBlueSVG =
      "assets/svg/check_circle_blue_svg.svg";
  static const String coinSVG = "assets/svg/coin.svg";
  static const String blueBulbSVG = "assets/svg/blue_bulb_svg.svg";
  static const String phoneIconTFSVG = "assets/svg/phone_icon_tf_svg.svg";
  static const String sbdEditIconSVG = "assets/svg/sbd_edit_icon_svg.svg";
  static const String piggyBankVerificationSVG =
      "assets/svg/piggy_bank_verification_svg.svg";
  static const String eMandatePollingSVG =
      "assets/svg/e_mandate_polling_svg.svg";
  static const String ifscTFIconSVG = "assets/svg/ifsc_tf_icon_svg.svg";
  static const String sblDisbursalProgressSVG =
      "assets/svg/sbl_disbursal_progress_svg.svg";
  static const String bankSelectionTFSvg =
      "assets/svg/bank_selection_tf_svg.svg";
  static const String accountNumberTFSvg =
      "assets/svg/account_number_tf_svg.svg";
  static const String confirmAccountNumberTFSvg =
      "assets/svg/confirm_account_number_tf_svg.svg";
  static const String pennyTestingBankBlueSVG =
      "assets/svg/penny_testing_bank_blue_svg.svg";
  static const String pennyTestingBankWhiteSVG =
      "assets/svg/penny_testing_bank_white_svg.svg";
  static const String stateTFIconSVG = "assets/svg/state_tf_icon_svg.svg";
  static const String cityTFIconSVG = "assets/svg/city_tf_icon_svg.svg";
  static const String addIcon = "assets/svg/add_icon.svg";
  static const String attachFileIcon = "assets/svg/attach_file_icon.svg";
  static const String businessNatureIcon =
      "assets/svg/business_nature_icon.svg";
  static const String businessSectorIcon =
      "assets/svg/business_sector_icon.svg";
  static const String fileEyeIcon = "assets/svg/file_eye_icon.svg";
  static const String fileDeleteIcon = "assets/svg/file_delete_icon.svg";
  static const String checkCircleBlue = "assets/svg/check_circle.svg";
  static const String checkCircleRed = "assets/svg/check_circle_red.svg";
  static const String retryIcon = "assets/svg/retry_icon.svg";
  static const String doc = "assets/svg/doc.svg";
  static const String getStartedClp = "assets/svg/get_started_clp.svg";
  static const String businessPollingSVG =
      "assets/svg/business_polling_svg.svg";
  static const String bankTransferIconSVG =
      "assets/svg/bank_transfer_icon_svg.svg";
  static const String cashIconSVG = "assets/svg/cash_icon_svg.svg";
  static const String netMonthlyIncomeTFIconSVG =
      "assets/svg/net_monthly_income_tf_icon_svg.svg";
  static const String sbdOfferGiftsSvg = "assets/svg/sbd_offer_gifts_svg.svg";
  static const String initialOfferBg = "assets/svg/initial_offer_bg.svg";
  static const String aaFailure = "assets/svg/aa_failure.svg";
  static const String locationRejectionSVG =
      "assets/svg/location_rejection_svg.svg";
  static const String kycRejectionSVG = "assets/svg/kyc_rejection_svg.svg";
  static const String generalRejectionSVG =
      "assets/svg/general_rejection_svg.svg";
  static const String panRejectionSVG = "assets/svg/pan_rejection_svg.svg";
  static const String doubleArrow = "assets/svg/doubleArrow.svg";
  static const String bankIconDarkBlueCircleSVG =
      "assets/svg/bank_icon_dark_blue_circle_svg.svg";
  static const String privoWalletWithMobile =
      "assets/svg/home_page/privo_wallet_with_mobile.svg";
  static const String coins = "assets/svg/home_page/coins.svg";
  static const String finSights = "assets/svg/home_page/finsights.svg";

  static const String authorize =
      "assets/svg/home_page/finsights/authorize.svg";
  static const String link = "assets/svg/home_page/finsights/link.svg";
  static const String manage = "assets/svg/home_page/finsights/manage.svg";
  static const String homePageEmiCalculatorIcon =
      "assets/svg/home_page/home_page_emi_calculator.svg";
  static const String financialToolSparkle =
      "assets/svg/home_page/financial_tool_sparkle.svg";

  // Final offer polling
  static const String pollingArrow =
      "assets/svg/final_offer_polling/polling_arrow.svg";
  static const String evaluatingBankDetailsImgSvg =
      "assets/svg/evaluate_Bank_Details_Img.svg";

  // Topup know more
  static const String topupCreditScore = "assets/svg/topup_credit_score.svg";
  static const String topupPayEarly = "assets/svg/topup_pay_early.svg";
  static const String topupTime = "assets/svg/topup_time.svg";
  static const String topupAmountTree = "assets/svg/topup_amount_tree.svg";
  static const String topupOutstandingBalanceTree =
      "assets/svg/topup_outstanding_balance_tree.svg";

  //Offer
  static const String topUpOffer = "assets/svg/offer/top_up_offer.svg";

  //offer zone
  static const String offerZoneHomePageSectionBGSVG =
      "assets/svg/offer_zone/offer_zone_home_page_section_bg_svg.svg";
  static const String offerZoneTextSVG =
      "assets/svg/offer_zone/offer_zone_text_svg.svg";
  static const String offerZoneTopUpCardSVG =
      "assets/svg/offer_zone/offer_zone_top_up_card_svg.svg";
  static const String offerZoneTopUpCardInProgressSVG =
      "assets/svg/offer_zone/offer_zone_top_up_card_in_progress_svg.svg";
  static const String topUpInitialOfferSVG =
      "assets/svg/offer_zone/top_up_initial_offer.svg";
  static const String lowGrowHomePageIllustrationSVG =
      "assets/svg/offer_zone/low_grow_home_page_illustration.svg";
  static const String topUpRejectionSVG =
      "assets/svg/offer_zone/top_up_rejection_svg.svg";

  //Finsights know more
  static const String enhancedCredit =
      "assets/svg/know_more/finsights/enhanced_credit.svg";
  static const String financialOverview =
      "assets/svg/know_more/finsights/financial_overview.svg";
  static const String insights = "assets/svg/know_more/finsights/insights.svg";
  static const String seamless = "assets/svg/know_more/finsights/seamless.svg";
  static const String finsightsKnowMore =
      "assets/svg/know_more/finsights/finsights_know_more.svg";
  static const String securityFirst =
      "assets/svg/know_more/finsights/security_first.svg";

  static const String clpKnowMoreBg =
      "assets/svg/know_more/clp/clp_know_more_bg.svg";
  static const String sblKnowMoreBg =
      "assets/svg/know_more/sbl/sbl_know_more_bg.svg";
  static const String clpKnowMore =
      "assets/svg/know_more/clp/know_more_clp.svg";
  static const String sblKnowMore =
      "assets/svg/know_more/sbl/know_more_sbl.svg";

  //Finsights
  static const String finsightsDashboardBGSvg =
      "assets/svg/finsights/finsights_dashboard_background_svg.svg";
  static const String finsightsDashboardEyeIconSvg =
      "assets/svg/finsights/finsights_dashboard_eye_icon_svg.svg";
  static const String finsightsDashboardClosedEyeIconSvg =
      "assets/svg/finsights/finsights_dashboard_closed_eye_icon_svg.svg";
  static const String finsightsAvgBalanceIconSvg =
      "assets/svg/finsights/finsights_avg_balance_icon_svg.svg";
  static const String finsightsAvgCreditIconSvg =
      "assets/svg/finsights/finsights_avg_credit_icon_svg.svg";
  static const String finsightsAvgDebitIconSvg =
      "assets/svg/finsights/finsights_avg_debit_icon_svg.svg";
  static const String finsightsCoinSvg =
      "assets/svg/finsights/coin_fin_sight.svg";
  static const String finsightsBottomBackgroundSvg =
      "assets/svg/finsights/finsights_bottom_background.svg";
  static const String finsightsNoTransactionsSvg =
      "assets/svg/finsights/finsights_no_transactions.svg";
  static const String finsightsBlue = "assets/svg/finsights/finsights_blue.svg";
  static const String finsights3Steps =
      "assets/svg/finsights/finsights_3_steps.svg";
  static const String finsightsFinancial =
      "assets/svg/finsights/finsights_financial.svg";

  //components
  static const String appBarBackIconSvg =
      "assets/svg/components/app_bar_back_icon_svg.svg";
  static const String appBarInfoIconSvg =
      "assets/svg/components/app_bar_info_icon_svg.svg";

  // Finsights
  static const String bankIllustration =
      "assets/svg/finsights/bank_illustration.svg";
  static const String bankIcon = "assets/svg/finsights/bank_icon.svg";
  static const String bankNotFound =
      "assets/svg/finsights/bank_not_found_svg.svg";
  static const String alertRedSVG = "assets/svg/finsights/alert_red_svg.svg";
  static const String finsightsIntroOnePNG =
      "assets/finsights/finsights_intro_one.png";
  static const String finsightsIntroTwoPNG =
      "assets/finsights/finsights_intro_two.png";
  static const String finsightsIntroThreePNG =
      "assets/finsights/finsights_intro_three.png";
  static const String finsightsIntroSocialProofPNG =
      "assets/finsights/finsights_intro_social_proof.png";
  static const String dropOffIllustration =
      "assets/svg/finsights/drop_off_illustration.svg";

//Credit score
  static const String creditEnquiriesSVG =
      "assets/svg/credit_report/credit_enquiries.svg";
  static const String creditMixSVG = "assets/svg/credit_report/credit_mix.svg";
  static const String creditScoreBankSVG =
      "assets/svg/credit_report/credit_score_bank.svg";
  static const String creditUtilisationSVG =
      "assets/svg/credit_report/credit_utilisation.svg";
  static const String onTimePaymentSVG =
      "assets/svg/credit_report/on_time_payment.svg";
  static const String creditAgeSvg = "assets/svg/credit_report/credit_age.svg";
  static const String creditReportArrow =
      "assets/svg/credit_report/credit_report_arrow.svg";
  static const String experian = "assets/svg/credit_report/experian.svg";
  static const String creditScoreBottomSheetSvg =
      "assets/svg/credit_report/credit_score_bottom_sheet_svg.svg";
  static const String refreshBulb = "assets/svg/credit_report/refresh_bulb.svg";
  static const arrowBack = "assets/svg/arrow_back.svg";
  static const String experianLogo =
      "assets/svg/credit_score/experian_logo.svg";
  static const String creditScoreInProgress =
      "assets/svg/credit_score/credit_score_in_progress.svg";
  static const String creditScoreSuccess =
      "assets/svg/credit_score/credit_score_success.svg";
  static const String creditScoreKnowMore =
      "assets/svg/credit_score/credit_score_know_more.svg";
  static const String creditScoreCheck =
      "assets/svg/credit_score/credit_score_check.svg";
  static const String creditScoreDataProtection =
      "assets/svg/credit_score/credit_score_data_protection.svg";
  static const String creditScoreFinancialHealth =
      "assets/svg/credit_score/credit_score_financial_health.svg";
  static const String creditScoreUpdates =
      "assets/svg/credit_score/credit_score_updates.svg";
  static const String businessCenter = "assets/svg/business_center.svg";
  static const String clpDisabledBackground = "assets/svg/clp_disabled_bg.svg";
  static const String experianD2cFrame =
      "assets/svg/credit_report/experian_d2c_frame.svg";
  static const String creditScoreKnowMoreV2 =
      "assets/svg/credit_score/credit_score_know_more_v2.svg";
  static const String creditScoreRefreshBottomSheetBg =
      "assets/svg/credit_score/credit_score_refresh_bottom_sheet_bg.svg";
  static const String creditScoreBottomSheetStarsSVG =
      "assets/svg/credit_score/credit_score_bottom_sheet_stars.svg";
  static const String creditScoreRefreshBottomSheetPeoplePNG =
      "assets/credit_score/credit_score_refresh_bottom_sheet_people.png";
  static const String creditScoreSlideInitialThumbSVG =
      "assets/svg/credit_score/credit_score_slide_initial_thumb.svg";
  static const String creditScoreSlideRefreshingThumbSVG =
      "assets/svg/credit_score/credit_score_slide_refreshing_thumb.svg";
  static const String creditScoreSlideRefreshedThumbSVG =
      "assets/svg/credit_score/credit_score_slide_refreshed_thumb.svg";
  static const String informationInfo = "assets/svg/icons/information_info.svg";

  //udyam
  static const String udyamHome = "assets/svg/udyam_home.svg";
  static const String doubleArrowRight = "assets/svg/double_arrow_right.svg";

  //Badges
  static const String badgeCheck =
      "assets/svg/components/badge/badge_check.svg";

  // bank logo
  static const String genericBankLogo = "assets/svg/bank_logos/generic.svg";
  static const String creditSaisonLogo = "assets/svg/bank_logos/cs.svg";
  static const String hdfcBankLogo = "assets/svg/bank_logos/hdfc.svg";
  static const String iciciBankLogo = "assets/svg/bank_logos/icici.svg";
  static const String sbiBankLogo = "assets/svg/bank_logos/sbi.svg";
  static const String axisBankLogo = "assets/svg/bank_logos/axis.svg";
  static const String kotakBankLogo = "assets/svg/bank_logos/kotak.svg";
  static const String bankOfBarodaLogo = "assets/svg/bank_logos/bob.svg";
  static const String punjabNationalBankLogo = "assets/svg/bank_logos/pnb.svg";
  static const String indianOverseasBankLogo =
      "assets/svg/bank_logos/indian_overseas_bank.svg";
  static const String unionBankLogo = "assets/svg/bank_logos/union_bank.svg";
  static const String canaraBankLogo = "assets/svg/bank_logos/canara.svg";
  static const String indusindBankLogo = "assets/svg/bank_logos/indusind.svg";
  static const String federalBankLogo = "assets/svg/bank_logos/federal.svg";
  static const String yesBankLogo = "assets/svg/bank_logos/yes.svg";
  static const String auSmallFinanceBankLogo =
      "assets/svg/bank_logos/au_small_finance.svg";
  static const String indianBankLogo = "assets/svg/bank_logos/indian_bank.svg";
  static const String idbiBankLogo = "assets/svg/bank_logos/idbi.svg";
  static const String centralBankOfIndiaLogo =
      "assets/svg/bank_logos/central_bank_of_india.svg";
  static const String experianDefaultBankLogo =
      "assets/svg/bank_logos/experian_default_bank_logo.svg";

  static const String shimmerEffectLineGraph =
      "assets/lottie/shimmer_line_graph.json";

  //icons
  static const String clock3Icon = "assets/svg/icons/clock_3.svg";
  static const String questionMark = "assets/svg/icons/question_mark.svg";
  static const String informationFilledIcon =
      "assets/svg/icons/information_filled.svg";
  static const String bankSmallSpaceIcon =
      "assets/svg/icons/bank_small_space.svg";
  static const String accordion1Icon = "assets/svg/icons/accordion_1.svg";
  static const String errorFilledIcon = "assets/svg/icons/error_filled.svg";
  static const String errorDialogIcon = "assets/svg/icons/error_dialog_icon.svg";
  static const String paymentSuccessIcon = "assets/svg/icons/payment_success_icon.svg";
  static const String alertFilledIcon = "assets/svg/icons/alert_filled.svg";
  static const String crossMarkIcon = "assets/svg/icons/cross_mark.svg";
  static const String accordingRight = "assets/svg/icons/accordian_right.svg";
  static const String copySimple = "assets/svg/icons/copy_simple.svg";
  static const String successGradient = "assets/svg/icons/success_gradient.svg";
  static const String copyIcon = "assets/svg/icons/copy_icon.svg";
  static const String faqIcon = "assets/svg/icons/faq_icon.svg";
  static const String sparkleDrawer = "assets/svg/icons/sparkle_drawer.svg";
  static const String help = "assets/svg/icons/help.svg";
  static const String verifiedSecured = "assets/svg/icons/verified_secured.svg";
  static const String downloadIcon = "assets/svg/icons/download.svg";
  static const String transactions = "assets/svg/icons/transactions.svg";
  static const String description = "assets/svg/icons/description.svg";
  static const String informationOutlined = "assets/svg/icons/information_outlined.svg";
  static const String failureTransaction = "assets/svg/failureTransaction.svg";
  static const String successTransaction = "assets/svg/successTransaction.svg";

  //loan details
  static const String loanAmountSVG =
      "assets/svg/loan_details/loan_amount_svg.svg";
  static const String emiAmountSVG =
      "assets/svg/loan_details/emi_amount_svg.svg";
  static const String loanListBGSVG =
      "assets/svg/loan_details/loan_list_bg.svg";

  // financial tools
  static const String emiCalculatorFinancialTools =
      "assets/svg/financial_tools/emi_calculator.svg";
  static const String emiCalculatoLargeFinancialTools =
      "assets/svg/financial_tools/emi_calculator_wide.svg";
  static const String creditScoreFinancialTools =
      "assets/svg/financial_tools/credit_score.svg";
  static const String finsightsRegularCardFinancialTools =
      "assets/svg/financial_tools/finsights_regular.svg";
  static const String finsightsLongCardFinancialTools =
      "assets/svg/financial_tools/finsights_long.svg";
  static const String bankAccountRegular =
      "assets/svg/financial_tools/bank_account_regular.svg";
  static const String bankAccountLong =
      "assets/svg/financial_tools/bank_account_long.svg";
  static const String nonEligibleFinsights =
      "assets/svg/nonEligibleFinsights.svg";

  // referral
  static const String referralHomeImage =
      "assets/svg/referral/referral_home_image.svg";
  static const String referralIntroOne =
      "assets/svg/referral/referral_intro_one.svg";
  static const String referralIntroTwo =
      "assets/svg/referral/referral_intro_two.svg";
  static const String referralIntroThree =
      "assets/svg/referral/referral_intro_three.svg";
  static const String referralGiftBox =
      "assets/svg/referral/referral_gift_box.svg";
  static const String referralWorkflowOne =
      "assets/svg/referral/referral_workflow_one.svg";
  static const String referralWorkflowTwo =
      "assets/svg/referral/referral_workflow_two.svg";
  static const String referralWorkflowThree =
      "assets/svg/referral/referral_workflow_three.svg";
  static const String referralLeaderBoard =
      "assets/svg/referral/leader_board.svg";
  static const String referralBellIcon =
      "assets/svg/referral/referral_bell_icon.svg";

  //account aggregator
  static const String loans = "assets/svg/icons/loans.svg";
  static const String finance = "assets/svg/icons/finance.svg";
  static const String clock2 = "assets/svg/icons/clock2.svg";
  static const String sahamatiLogo1 = "assets/svg/primary_logo3.svg";
  static const String aaBankSuccess = "assets/svg/aa_bank_success.svg";

  static const String redirectFailure = "assets/svg/redirect_failure.svg";
  static const String nonEligibleFinSights_one =
      "assets/svg/non_eligible_finsights/non_finsights_1.svg";
  static const String nonEligibleFinSights_two =
      "assets/svg/non_eligible_finsights/non_finsights_2.svg";
  static const String nonEligibleFinSights_three =
      "assets/svg/non_eligible_finsights/non_finsights_3.svg";
  static const String nonEligibleGridOne =
      "assets/svg/non_eligible_finsights/non_eligible_grid_one.svg";
  static const String nonEligibleGridTwo =
      "assets/svg/non_eligible_finsights/non_eligible_grid_two.svg";
  static const String nonEligibleGridThree =
      "assets/svg/non_eligible_finsights/non_eligible_grid_three.svg";
  static const String nonEligibleGridFour =
      "assets/svg/non_eligible_finsights/non_eligible_grid_four.svg";
  static const String calenderToday =
      "assets/svg/non_eligible_finsights/calendar_today.svg";
  static const String payments =
      "assets/svg/non_eligible_finsights/payments.svg";
  static const String receiptLong =
      "assets/svg/non_eligible_finsights/receipt_long.svg";
  static const String security =
      "assets/svg/non_eligible_finsights/security.svg";
  static const String waitListImage =
      "assets/svg/non_eligible_finsights/waitlistImage.svg";
  static const String waitImageTwo =
      "assets/svg/non_eligible_finsights/waitImageTwo.svg";
  static const String nonFinSightDarkImg =
      "assets/svg/non_eligible_finsights/nonFinSightDarkImage.svg";
  static const String coinBank =
      "assets/svg/non_eligible_finsights/coin_bank.svg";
  static const String coinFinance =
      "assets/svg/non_eligible_finsights/coin_finance.svg";
  static const String nonEligibleBgImg =
      "assets/svg/non_eligible_finsights/nonEligibleBgImg.svg";
  static const String nonEligibleBgImgTwo =
      "assets/svg/non_eligible_finsights/non_finsight_bg_image_two.svg";
  static const String bgsparkles = "assets/bgSparkles.png";
  static const String overDueAlertBulb = "assets/svg/overdue_alert_bulb.svg";
  static const String nothingToSeeHere = "assets/svg/nothingToSeeHere.svg";
  static const String crossWhite = "assets/svg/crossWhite.svg";
  static const String crossButton = "assets/svg/CrossButton.svg";

  static const String smartphone = "assets/svg/smartphone.svg";
  static const String spendingCalender = "assets/svg/spending_calender.svg";
  static const String spendingShopping = "assets/svg/spending_shopping.svg";
  static const String highestSpending = "assets/svg/highestSpending.svg";
  static const String lowestSpending = "assets/svg/lowestSpending.svg";
  static const String rsIcon = "assets/svg/rs_icon.svg";
  static const String leaderboard = "assets/svg/leaderboard.svg";
  static const String spendingBg = "assets/svg/spendingBg.svg";
  static const String creditScoreDetailsImg =
      "assets/svg/creditScoreDetailsImg.svg";
  static const String circleRight = "assets/svg/expand_circle_right.svg";
  static const String emi_icon = "assets/svg/spending_snapshot/emi_icon.svg";
  static const String loan_icon = "assets/svg/spending_snapshot/loan_icon.svg";
  static const String transferTo =
      "assets/svg/spending_snapshot/transferTo.svg";
  static const String transfer_from =
      "assets/svg/spending_snapshot/transfer_from.svg";
  static const String withdraw_icon =
      "assets/svg/spending_snapshot/withdraw_icon.svg";
  static const String creditcardPayment =
      "assets/svg/spending_snapshot/creditcardPayment.svg";
  static const String lunch_dining =
      "assets/svg/spending_snapshot/lunch_dining.svg";
  static const String luggage = "assets/svg/spending_snapshot/luggage.svg";
  static const String local_taxi =
      "assets/svg/spending_snapshot/local_taxi.svg";
  static const String bed = "assets/svg/spending_snapshot/bed.svg";
  static const String entertainment =
      "assets/svg/spending_snapshot/entertainment.svg";
  static const String shopping_bag =
      "assets/svg/spending_snapshot/shopping_bag.svg";
  static const String utility = "assets/svg/spending_snapshot/utility.svg";
  static const String investment =
      "assets/svg/spending_snapshot/investment.svg";
  static const String cardiology =
      "assets/svg/spending_snapshot/cardiology.svg";
  static const String cottage = "assets/svg/spending_snapshot/cottage.svg";
  static const String spa = "assets/svg/spending_snapshot/spa.svg";
  static const String dictionary =
      "assets/svg/spending_snapshot/dictionary.svg";
  static const String category = "assets/svg/spending_snapshot/category.svg";
  static const String noSpendingData =
      "assets/svg/spending_snapshot/no_spending.svg";
  static const String ignosisBg = "assets/svg/finsights/ignosisBg.svg";
  static const String electric_bolt = "assets/svg/finsights/electric_bolt.svg";
  static const String ignosis_search =
      "assets/svg/finsights/ignosis_search.svg";
  static const String mobileEWallet =
      "assets/svg/finsights/mobileEWallet.svg";
  static const String mobileInfo =
      "assets/svg/finsights/mobile_info.svg";
  static const String lock = "assets/svg/lock.svg";
  static const String clearDues = "assets/svg/clearDues.svg";

  ///Refree
  static const String referralCode = "assets/svg/refree/referral_code.svg";
  static const String welcomeCelebration =
      "assets/svg/refree/welcome_celebration.svg";
  static const String referralBusiness =
      "assets/svg/refree/referral_business.svg";
  static const String referralCreditScore =
      "assets/svg/refree/referral_credit_score.svg";
  static const String referralEmiCalculator =
      "assets/svg/refree/referral_emi_calculator.svg";

  static const String homeDrawer = "assets/svg/home_drawer.svg";
  static const String knowledgeBaseDrawer = "assets/svg/k_base_drawer.svg";
  static const String logoutDrawer = "assets/svg/logout.svg";
  static const String hsupportDrawer = "assets/svg/h_support_drawer.svg";
  static const String rfriendDrawer = "assets/svg/r_friend_drawer.svg";

  static const String shoppingIconFinsights =
      "assets/svg/finsights/shopping_icon_finsights.svg";

  static const String trendingUp = "assets/svg/credit_score/trending_up.svg";

  static const String rightArrowCreditScore =
      "assets/svg/credit_score/right_arrow_credit_score.svg";
  static const String creditScoreImg =
      "assets/svg/credit_score/credit_score_img.svg";
  static const String trendingDown =
      "assets/svg/credit_score/trending_down.svg";
  static const String waitObject = "assets/svg/finsights/wait_object.svg";
  static const String info = "assets/svg/finsights/info.svg";
}
