late List<String> businessSectorsList = [
  "Chemicals",
  "Consumer durables/White goods and electronics",
  "Mobile phones",
  "FMCG including frozen food",
  "Pharmacy (not ayurvedic) and medical/surgical equipment",
  "IT hardware and peripherals incl. automation devices",
  "Industrial hardware/machinery tools",
  "E-commerce",
  "Plastic",
  "Electrical items",
  "Ceramic, Glass and Hardware (including paints)",
  "Cosmetics and personal healthcare items, home gift items including utensils and toys and sport products",
  "Textile and apparels (including job work)",
  "Stationery items (Not more than 50% supply to schools)",
  "Footwears",
  "Home furnishings, furniture and décor",
  "Automobile and auto components",
  "Paper and printing (except Books, publishing house)",
  "Metals manufacturing/trading with stock",
  "Agri commodity/ Dairy business",
  "Food and Restaurants (including bakery)",
  "Manpower supply (skilled only)",
  "IT software and solutions",
  "Logistics/Transportation with more than 3 owned vehicles",
  "Oil and Natural gas (including Petrol pumps)",
  "Advertising and digital marketing",
  "Packaging",
  "Hospitals & Diagnostic centers",
  "Consultancy and service providers (non-contractors)",
  "Civil and construction contractors (both government and private)",
  "Security agencies",
  "Educational/Training institutes (professional courses except schools)",
  "Telecom",
  "Travel related/ ticketing/ travel agents etc.",
  "Hotels (except restaurants)",
  "Real estate business or services to any real estate business",
  "Commission/ MLM business",
  "Chit fund/private finance business",
  "Massage parlors",
  "Cable TV business/operators",
  "Courier companies",
  "Film industry",
  "Collection agencies",
  "DSA",
  "Jewellery business (both real and imitation)",
  "Metal traders- without stock",
  "Scrap dealers/traders",
  "Building material suppliers",
  "Petrol Pumps",
  "Others"
];
